export const SourceMap = {
    arangscans: 'Arang Scans',
    bacamanga: 'Bacamanga',
    bangaqua: 'Bang Aqua',
    thecatscans: 'The Cat Scans',
    chibimanga: 'ChibiManga',
    deathtollscans: 'Death Toll Scans',
    disasterscans: 'Disaster Scans',
    dm5: 'DM5',
    dokireader: 'Doki Reader',
    dokusha: 'Dokusha',
    dynastyscans: 'Dynasty Scans',
    earlymanga: 'EarlyManga',
    easygoing: 'Easy Going',
    edelgardescans: 'Edelgarde Scans',
    elpsykongroo: 'Elpsykongroo',
    evilflowers: 'Evil Flowers',
    fallenangels: 'Fallen Angels',
    forgottenscans: 'Forgotten Scans',
    funmanga: 'FunManga',
    gekkouscans: 'Gekkou Scans',
    gufengmh8: 'GuFengMH8',
    hastareader: 'Hasta Reader',
    hatigarmscans: 'Hatigarm Scans',
    helveticascans: 'Helvetica Scans',
    heromanhua: 'Hero Manhua',
    hunlightscans: 'Hunlight Scans',
    isekaiscans: 'IsekaiScans',
    itascan: 'ItaScan',
    jaiminisbox: 'Jaimini\'s Box',
    kangaryuteam: 'Kangaryu Team',
    kireicake: 'Kirei Cake',
    kiryuu: 'Kiryuu',
    kkjscans: 'KKJ Scans',
    komikav: 'Komikav',
    komicast: 'Komicast',
    komikgo: 'Komikgo',
    komikgue: 'Komikgue',
    komikid: 'Komikid',
    komikindo: 'Komikindo',
    komikstation: 'Komikstation',
    komiku: 'Komiku',
    letitgoscans: 'Let It Go Scans',
    leviatanscans: 'Leviatan Scans',
    lhtranslations: 'LHTranslations',
    loveheaven: 'Love Heaven',
    manga4life: 'Manga4Life',
    'mangaal-arab': 'Manga Al-arab',
    mangachan: 'Mangachan',
    mangadex3mangasinlist: 'MangaDex 3 mangas in list',
    mangadods: 'Manga Dods',
    'manga-fox': 'Manga-Fox',
    mangahasu: 'Manga Hasu',
    mangahere: 'Manga Here',
    mangahost: 'MangaHost',
    mangahub: 'Manga Hub',
    mangaichiscans: 'Mangaichi Scans',
    mangainn: 'MangaInn',
    mangakakalot: 'Mangakakalot',
    mangalib: 'MangaLib',
    manganelo: 'Manganelo',
    mangapanda: 'Manga Panda',
    mangareader: 'Manga Reader',
    mangarock: 'Manga Rock',
    mangasee: 'MangaSee',
    mangashiro: 'Mangashiro',
    mangastream: 'MangaStream',
    mangasushi: 'Manga Sushi',
    mangaturf: 'Manga Turf',
    mangaturk: 'Manga Turk',
    mangazukime: 'MangazukiMe',
    mangazuki: 'Mangazuki',
    mangazukiinfo: 'MangazukiInfo',
    manhuaplus: 'ManhuaPlus',
    manhuas: 'Manhuas',
    manhuaus: 'Manhuaus',
    manhwaclub: 'ManhwaClub',
    manwha18: 'Manwha 18',
    manytoon: 'Manytoon',
    martialscans: 'Martial Scans',
    merakiscans: 'MerakiScans',
    methodscans: 'Method Scans',
    mintmanga: 'MintManga',
    naniscans: 'Nani Scans',
    neumanga: 'Neumanga',
    ngomik: 'Ngomik',
    niceoppai: 'Niceoppai',
    nightcomic: 'Night Comic',
    ninjascans: 'NinjaScans',
    thenonames: 'The No Names',
    nonstopscans: 'Non Stop Scans',
    onetimescans: 'One Time Scans',
    pecintakomik: 'Pecintakomik',
    phoenixserenade: 'Phoenix Serenade',
    pmscans: 'PM Scans',
    projecttimescans: 'Project Time Scans',
    'readm.org': 'Readm.org',
    readmanga: 'ReadManga',
    readmangatoday: 'ReadMangaToday',
    readmanhua: 'Read Manhua',
    reaperscans: 'Reaper Scans',
    roseliascans: 'Roselia Scans',
    scanfr: 'ScanFR',
    scantrad: 'Scan Trad',
    secretscans: 'Secret Scans',
    sensesscans: 'Senses Scans',
    shoujohearts: 'Shoujo Hearts',
    skscans: 'SK Scans',
    sorcererweekly: 'Sorcerer Weekly',
    submanga: 'SubManga',
    tappytappytap: 'Tappy tappy tap',
    toonily: 'Toonily',
    twistedhelscans: 'Twisted Hel Scans',
    ultmanga: 'Ult Manga',
    unionleitor: 'Union Leitor',
    vortexscans: 'Vortex Scans',
    webtoons: 'WebToons',
    westmanga: 'Westmanga',
    worldthree: 'World Three',
    yomanga: 'Yomanga',
    zeroscans: 'Zero Scans'
  }